services:
  app:
    image: ghcr.io/nizamovedik/laravel_ai:latest
    container_name: project_ai_app
    restart: always
    env_file:
      - .env
    volumes:
      - storage_data:/var/www/storage
      # Создаем именованный volume для папки public, чтобы поделиться ей с Nginx
      - public_data:/var/www/public 
      - ./.env:/var/www/.env 
    depends_on:
      - db
      - redis
    networks:
      - project_network

  nginx:
    image: nginx:latest
    container_name: project_ai_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Подключаем ту самую папку public из контейнера app
      - public_data:/var/www/public:ro
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/live/nizamov-eduard.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/nizamov-eduard.ru/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - app
    networks:
      - project_network

  db:
    image: mysql:8.4
    container_name: project_ai_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: laravel_ai_docker
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - project_network

  redis:
    image: redis:7-alpine
    container_name: project_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - project_network

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  storage_data:
    driver: local
  # Объявляем новый volume для статики
  public_data:
    driver: local

networks:
  project_network:
    driver: bridge
