services:
  app:
    image: ghcr.io/nizamovedik/laravel_ai:latest
    container_name: project_ai_app
    restart: always
    env_file:
      - .env
    volumes:
      - storage_data:/var/www/storage
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    container_name: project_ai_nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/nizamov-eduard.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/nizamov-eduard.ru/privkey.pem:/etc/nginx/ssl/privkey.pem:ro

  db:
    image: mysql:8.4
    container_name: project_ai_db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  redis:
    image: redis:7-alpine
    container_name: project_redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  storage_data:
    driver: local